apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop-demo
  #replica set labels
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  replicas: 1
  selector:
  # labels to select pods
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: db
    #pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: db 
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: roboshop
        - name: RABBITMQ_DEFAULT_PASS
          value: roboshop123
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop-demo
spec:
  selector:
    project: roboshop
    component: rabbitmq
    tier: db
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672