apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop-demo
  #replica set labels
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
  # labels to select pods
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
    #pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db 
    spec:
      containers:
      - name: mongodb
        image: docker4rajashekar/mongodb:v1
        imagepullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop-demo
spec:
  selector:
    project: roboshop
    component: mongodb
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017